# Decompile every case in manifest.json against a real, externally-supplied
# .so and score the structural shape of the output.
#
# This is the L1 tier: unlike eval/, these binaries were not built from known
# C, so there is no signature or type ground truth to check against. What is
# checked is shape -- gotos, switches, ternaries -- and whether the decompile
# itself succeeds within the case's round budget. A case's binary is resolved
# through samples/local.json (gitignored, one .so per machine) or an
# XDEC_SAMPLE_<KEY> environment variable, never a path checked into the repo.
param(
  [string]$Xdec = (Join-Path (Split-Path $PSScriptRoot -Parent) "build\dev\bin\xdec.exe"),
  [int]$Rounds = 8,
  [string]$LocalConfig = (Join-Path $PSScriptRoot "local.json"),
  # Compares against a stored run and fails on any case that used to pass.
  [string]$Baseline,
  # Overwrites the baseline with this run instead of comparing against it.
  [switch]$UpdateBaseline
)

$ErrorActionPreference = "Stop"
$Root = $PSScriptRoot
$Build = Join-Path $Root "build"
$Out = Join-Path $Build "out"
$Manifest = Join-Path $Root "manifest.json"
$Report = Join-Path $Build "report.json"
$CombinedPath = Join-Path $Build "all.c"
$Log = Join-Path $Build "run.log"
if (-not $Baseline) {
  $Baseline = Join-Path $Root "baseline.json"
}

if (-not (Test-Path $Xdec)) {
  throw "xdec not found: $Xdec`nBuild xdec first (cmake --build build/dev)."
}

New-Item -ItemType Directory -Force -Path $Out | Out-Null
"" | Set-Content $Log

$manifestData = Get-Content $Manifest -Raw | ConvertFrom-Json

$localPaths = @{}
if (Test-Path $LocalConfig) {
  $localData = Get-Content $LocalConfig -Raw | ConvertFrom-Json
  $localData.PSObject.Properties | Where-Object { $_.Name -ne "_comment" } | ForEach-Object {
    $localPaths[$_.Name] = $_.Value
  }
}

function Resolve-SampleBinary([string]$Key) {
  $envName = "XDEC_SAMPLE_$($Key.ToUpperInvariant())"
  $envPath = [Environment]::GetEnvironmentVariable($envName)
  if ($envPath) { return $envPath }
  if ($localPaths.ContainsKey($Key)) { return $localPaths[$Key] }
  return $null
}

Write-Host "Decompiling $($manifestData.cases.Count) case(s) with $Xdec ..."
$errors = @()
$skipped = @()
$scored = @()
$chunks = @(
  "/* xdec L1 samples - generated by samples/run.ps1 */",
  "#include <stdint.h>",
  ""
)

foreach ($case in $manifestData.cases) {
  if ($case.PSObject.Properties['enabled'] -and -not $case.enabled) {
    $skipped += "$($case.name) (disabled)"
    continue
  }
  $binaryPath = Resolve-SampleBinary $case.binary
  if (-not $binaryPath -or -not (Test-Path $binaryPath)) {
    $skipped += "$($case.name) (binary '$($case.binary)' not found -- add it to samples/local.json or set XDEC_SAMPLE_$($case.binary.ToUpperInvariant()))"
    continue
  }

  $rounds = if ($case.PSObject.Properties['rounds']) { $case.rounds } else { $Rounds }
  $extra = if ($case.PSObject.Properties['decompile_args']) { @($case.decompile_args) } else { @() }
  $outFile = Join-Path $Out ("{0}.c" -f $case.name)
  $cliArgs = @($binaryPath, $case.address, "-o", $outFile, "--rounds", $rounds) + $extra

  Write-Host "  $($case.name) @ $($case.address) (rounds=$rounds)"
  $sw = [Diagnostics.Stopwatch]::StartNew()
  # Under ErrorActionPreference=Stop, merging a native command's stderr turns
  # any diagnostic it writes into a terminating error -- and a case that
  # decompiles successfully while warning about what it had to seal is exactly
  # the case this suite exists to score. The exit code is the verdict here.
  $prevPreference = $ErrorActionPreference
  $ErrorActionPreference = "Continue"
  $output = & $Xdec decompile @cliArgs 2>&1
  $ErrorActionPreference = $prevPreference
  $sw.Stop()
  Add-Content $Log "$($case.name) $($case.address) exit=$LASTEXITCODE time=$([int]$sw.Elapsed.TotalSeconds)s args=$($extra -join ' ')"
  Add-Content $Log ($output -join "`n")
  if ($LASTEXITCODE -ne 0 -or -not (Test-Path $outFile)) {
    $errors += "$($case.name): decompile failed (exit=$LASTEXITCODE)"
    continue
  }
  $scored += $case.name
  $chunks += "// ========== $($case.name) @ $($case.address) =========="
  $chunks += (Get-Content $outFile -Raw)
  $chunks += ""
}

$chunks -join "`n" | Set-Content -Encoding utf8 $CombinedPath

if ($skipped.Count -gt 0) {
  Write-Host ""
  Write-Host "Skipped $($skipped.Count):"
  $skipped | ForEach-Object { Write-Host "  $_" }
}

Write-Host ""
Write-Host "Scoring..."
$scoreArgs = @((Join-Path $Root "score.py"), $Manifest, $CombinedPath, $Report)
if ($UpdateBaseline) {
  python @scoreArgs
  $scoreExit = $LASTEXITCODE
  Copy-Item $Report $Baseline -Force
  Write-Host "Baseline updated: $Baseline"
} else {
  python @scoreArgs --baseline $Baseline
  $scoreExit = $LASTEXITCODE
}

Write-Host ""
Write-Host "Per-function outputs: $Out"
Write-Host "Combined: $CombinedPath"
Write-Host "Log: $Log"

if ($errors.Count -gt 0) {
  Write-Host ""
  Write-Host "Decompile errors:"
  $errors | ForEach-Object { Write-Host "  $_" }
}

if ($errors.Count -gt 0 -and $scored.Count -eq 0) {
  # Nothing decompiled at all -- a config problem, not a scoring result.
  exit 2
}

exit $scoreExit
