// Execution-oriented packets compiled from xspec-produced Lifted IL.
#pragma once

#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "xdec/exec/memory.h"
#include "xdec/spec/engine.h"
#include "xdec/spec/lift.h"

namespace xdec::exec {

struct ExecInstruction {
  uint64_t pc = 0;
  uint64_t word = 0;
  unsigned length = 0;
  std::string disassembly;
  spec::InsnFlow flow;
  std::vector<il::OpId> ops;
};

struct CodePageStamp {
  uint64_t page = 0;
  uint64_t generation = 0;
};

/// A cached executable block whose operations were generated by xspec.
///
/// This is intentionally a small first ExecIR: it groups Lifted IL by source
/// machine instruction while preserving one semantic source. A future compact
/// micro-op representation can replace the owned LiftedBlock behind this API.
struct ExecBlock {
  spec::LiftedBlock lifted;
  std::vector<ExecInstruction> instructions;
  std::vector<CodePageStamp> codePages;

  [[nodiscard]] bool validFor(const GuestAddressSpace& memory) const;
  [[nodiscard]] const ExecInstruction* instructionAt(uint64_t pc) const;
};

[[nodiscard]] Result<std::shared_ptr<ExecBlock>> compileExecBlock(
    const spec::SpecEngine& engine, const GuestAddressSpace& memory, uint64_t pc,
    std::size_t maxInstructions = 256);

}  // namespace xdec::exec
