// Execution-oriented packets compiled from xspec-produced Lifted IL.
#pragma once

#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "xdec/exec/insn_semantics.h"
#include "xdec/exec/memory.h"
#include "xdec/spec/engine.h"
#include "xdec/spec/lift.h"

namespace xdec::exec {

/// One register an instruction names, as the instruction names it: `w0` stays
/// `w0` rather than collapsing to `x0`, so a consumer can tell a 32-bit write
/// from a 64-bit one.
struct RegisterOperand {
  il::RegId reg;
  bool write = false;
};

struct ExecInstruction {
  uint64_t pc = 0;
  uint64_t word = 0;
  unsigned length = 0;
  std::string disassembly;
  /// Lowercased opcode, e.g. "ldr" out of "ldr x0, [x1]". Computed once here
  /// instead of by every observer on every execution of a hot loop's body.
  std::string mnemonic;
  spec::InsnFlow flow;
  std::vector<il::OpId> ops;
  /// Every register the instruction reads, then every one it writes, taken
  /// from the lifted ReadReg/WriteReg ops. This is a property of the encoding,
  /// not of one execution, so it is resolved once here rather than rediscovered
  /// each time a hot loop's body comes around. Duplicates within a direction
  /// are folded: naming x0 twice still describes one operand.
  std::vector<RegisterOperand> registerOperands;
  /// Where the writes begin in registerOperands; everything before is a read.
  std::size_t firstWriteOperand = 0;
  /// What the instruction computes, flattened out of `ops` so that a consumer
  /// outside the process gets the lifter's answer instead of decoding the word
  /// again. Like registerOperands, a property of the encoding and so resolved
  /// once here.
  InstructionSemantics semantics;
};

struct CodePageStamp {
  uint64_t page = 0;
  uint64_t generation = 0;
};

/// A cached executable block whose operations were generated by xspec.
///
/// This is intentionally a small first ExecIR: it groups Lifted IL by source
/// machine instruction while preserving one semantic source. A future compact
/// micro-op representation can replace the owned LiftedBlock behind this API.
struct ExecBlock {
  spec::LiftedBlock lifted;
  std::vector<ExecInstruction> instructions;
  std::vector<CodePageStamp> codePages;
  /// Root registers the block's WriteReg ops target, resolved while lifting.
  /// WriteReg is the interpreter's only way into the register file, so this
  /// covers every register an execution of this block can change -- a superset
  /// when a path is not taken, which is all a caller mirroring registers
  /// elsewhere needs. Computed once per compile rather than tracked per write.
  std::vector<il::RegId> writtenRoots;

  [[nodiscard]] bool validFor(const GuestAddressSpace& memory) const;
  [[nodiscard]] const ExecInstruction* instructionAt(uint64_t pc) const;
};

[[nodiscard]] Result<std::shared_ptr<ExecBlock>> compileExecBlock(
    const spec::SpecEngine& engine, const GuestAddressSpace& memory, uint64_t pc,
    std::size_t maxInstructions = 256);

}  // namespace xdec::exec
